/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spencerbharath' at '11/5/16 12:27 PM' with Gradle 3.1
 *
 * @author spencerbharath, @date 11/5/16 12:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
